openapi: 3.1.0
info:
  title: Gearit-api
  description: Gearit-api
  version: 0.1.1
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: Auth
    description: Аутентификация/Авторизация/Регистрация пользователей в системе
  - name: Profile
    description: Операции с профилем пользователя
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Регистрация
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        200:
          description: Успешная регистрация.
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

  /auth/verify:
    get:
      tags:
        - Auth
      summary: Регистрация
      parameters:
        - name: code
          in: path
          description: Код подтверждения, отправленный на почту
          required: true
          schema:
            type:
              - string
      responses:
        200:
          description: Успешная верификация аккаунта
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

  /auth/login:
    post:
      tags:
        - Auth
      summary: Авторизация
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: Успешная аутентификация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

  /auth/token/refresh:
    post:
      tags:
        - Auth
      summary: Обновление токена доступа
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      responses:
        200:
          description: Успешная регистрация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

  /yandex/login:
    get:
      tags:
        - Auth
      summary: Авторизация через сервер OAuth Yandex
      responses:
        200:
          description: Успешное получение редиректа
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

  /yandex/callback:
    get:
      tags:
        - Auth
      summary: Авторизация через сервер OAuth Yandex
      responses:
        200:
          description: Успешное добавление пользователя в БД и получение токенов доступа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

components:
  schemas:
    ClientException:
      type:
        - object
      properties:
        message:
          type:
            - string
          example: 'Неверный логин'
        extendedHelp:
          type:
            - string
          example: 'Измените логин и попробуйте ещё раз'

    RegisterRequest:
      type:
        - object
      properties:
        password:
          type:
            - string
        email:
          type:
            - string

    LoginRequest:
      type:
        - object
      properties:
        email:
          type:
            - string
        password:
          type:
            - string

    TokenRequest:
      type:
        - object
      properties:
        refreshToken:
          type:
            - string

    TokenResponse:
      type:
        - object
      properties:
        accessToken:
          type:
            - string
        refreshToken:
          type:
            - string
