openapi: 3.1.0
info:
  title: gearit-api
  description: gearit-api
  version: 0.1.1
servers:
  - url: 'http://localhost:8080/api/v1'
tags:
  - name: Auth
    description: Аутентификация/Авторизация/Регистрация пользователей в системе
  - name: Profile
    description: Операции с профилем пользователя
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Регистрация
      operationId: register
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
      responses:
        200:
          description: Успешная регистрация.
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

  /auth/verify:
    get:
      tags:
        - Auth
      summary: Регистрация
      operationId: verify
      security: []
      parameters:
        - name: code
          in: query
          description: Код подтверждения, отправленный на почту
          required: true
          schema:
            type:
              - string
      responses:
        200:
          description: Успешная верификация аккаунта
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

  /auth/login:
    post:
      tags:
        - Auth
      summary: Авторизация
      operationId: login
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        200:
          description: Успешная аутентификация.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        400:
          description: Если были переданы некорректные данные.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

  /auth/token/refresh:
    post:
      tags:
        - Auth
      summary: Обновление токена доступа
      operationId: refresh
      security: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      responses:
        200:
          description: Успешная регистрация.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

  /password/forgot:
    post:
      tags:
        - Password operation
      summary: Отправка уведомления о восстановление пароля на почту
      operationId: passwordForgot
      security: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ForgotRequest'
      responses:
        200:
          description: Успешная отправка уведомления.
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

  /password/verify-code:
    post:
      tags:
        - Password operation
      summary: Проверка на валидность отправленного кода для восстановления пароля
      operationId: passwordVerifyCode
      security: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VerifyCodeRequest'
      responses:
        200:
          description: Успешная отправка уведомления.
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

  /password/reset:
    post:
      tags:
        - Password operation
      summary: Обновление пароля пользователя
      operationId: passwordReset
      security: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ResetPasswordRequest'
      responses:
        200:
          description: Успешная отправка уведомления.
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

  /yandex/login:
    get:
      tags:
        - Auth
      summary: Авторизация через сервер OAuth Yandex
      operationId: yandex/login
      security: []
      responses:
        200:
          description: Успешное получение редиректа
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

  /yandex/callback:
    get:
      tags:
        - Auth
      summary: Авторизация через сервер OAuth Yandex
      operationId: yandex/callback
      security: []
      responses:
        200:
          description: Успешное добавление пользователя в БД и получение токенов доступа
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenResponse'
        400:
          description: Если были переданы некорректные данные
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"
        500:
          description: Ошибка сервера
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ClientException"

components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    ClientException:
      type:
        - object
      properties:
        message:
          type:
            - string
          example: 'Incorrect user data'
        extendedHelp:
          type:
            - string
          example: 'Password cannot be null or empty'

    RegisterRequest:
      type:
        - object
      properties:
        password:
          type:
            - string
        email:
          type:
            - string

    LoginRequest:
      type:
        - object
      properties:
        email:
          type:
            - string
        password:
          type:
            - string

    TokenRequest:
      type:
        - object
      properties:
        refreshToken:
          type:
            - string

    TokenResponse:
      type:
        - object
      properties:
        accessToken:
          type:
            - string
        refreshToken:
          type:
            - string

    ForgotRequest:
      type:
        - object
      properties:
        email:
          type:
            - string

    VerifyCodeRequest:
      type:
        - object
      properties:
        code:
          type:
            - string

    ResetPasswordRequest:
      type:
        - object
      properties:
        code:
          type:
            - string
        password:
          type:
            - string