server.port=8080
spring.application.name=gearit-backend
server.forward-headers-strategy=native

#---
spring.profiles.active=production
yandex.properties.redirect-uri=https://api.gearit.ru/api/v1/yandex/callback
#---
spring.profiles.active=develop
yandex.properties.redirect-uri==https://api.gearit.ru/api/v1/yandex/callback
#---


# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog/db.changelog-master.yaml
spring.liquibase.database-change-log-table=gearit_changelog
spring.liquibase.database-change-log-lock-table=gearit_changelog_lock

# Database properties
spring.datasource.url=jdbc:postgresql://localhost:5433/gearit
spring.datasource.username=gearit
spring.datasource.password=gearit

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

email.properties.resend-token=re_TVBU3oBi_9Zq6hPBm6x7KJtw7yFqgQT39
email.properties.from=onboarding@resend.dev

yandex.properties.client-id=b786f5076cfb40cbafd82f3d2b36aeae
yandex.properties.client-secret=16c95cc9d1c2460abaa7534c022d1a5e
yandex.properties.auth-uri=https://oauth.yandex.ru/authorize
yandex.properties.token-uri=https://oauth.yandex.ru/token
yandex.properties.user-info-uri=https://login.yandex.ru/info