server.port=8080
spring.application.name=gearit-backend
server.forward-headers-strategy=native

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db.changelog/db.changelog-master.yaml
spring.liquibase.database-change-log-table=gearit_changelog
spring.liquibase.database-change-log-lock-table=gearit_changelog_lock

# Database properties
spring.datasource.url=jdbc:postgresql://localhost:5432/gearit
spring.datasource.username=gearit
spring.datasource.password=gearit

spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:init.db/data.sql

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

# Email sender settings
email.properties.resend-token=${RESEND_TOKEN}
email.properties.from=${FROM}
email.properties.url-verify=${URL_VERIFY:http://localhost:3000/register/verify?code=}

# Yandex OAuth
yandex.properties.client-id=${CLIENT_ID}
yandex.properties.client-secret=${CLIENT_SECRET}
yandex.properties.redirect-uri=${REDIRECT_URI:http://localhost:3000/yandex/login}
yandex.properties.auth-uri=https://oauth.yandex.ru/authorize
yandex.properties.token-uri=https://oauth.yandex.ru/token
yandex.properties.user-info-uri=https://login.yandex.ru/info

# CORS
cors.properties.cors-allowed-origins-uri=${CORS_ALLOWED_ORIGINS_URI:http://localhost:3000}

# Spring actuator
management.endpoints.web.exposure.include=prometheus,info,status
management.prometheus.metrics.export.enabled=true
