services:

  gearit-data:
    container_name: gearit-data
    image: ghcr.io/danil-prog/gearit-data:16.3
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      TZ: "Asia/Novosibirsk"
    ports:
      - "5433:5432"
    networks:
      - gearit-network

  gearit-backend:
    container_name: gearit-backend
    image: ghcr.io/danil-prog/gearit-backend:latest
    environment:
      SPRING_PROFILES_ACTIVE: "develop"

      #  Database config
      SPRING_DATASOURCE_URL: "jdbc:postgresql://gearit-data:5432/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: "${DB_USERNAME}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"

      # Mail sender
      EMAIL_PROPERTIES_RESEND_TOKEN: "${RESEND_TOKEN}"
      EMAIL_PROPERTIES_FROM: "${FROM}"
      EMAIL_PROPERTIES_URL_VERIFY: "${URL_VERIFY}"

      # Yandex OAuth2
      YANDEX_PROPERTIES_CLIENT_ID: "${CLIENT_ID}"
      YANDEX_PROPERTIES_CLIENT_SECRET: "${CLIENT_SECRET}"
      YANDEX_PROPERTIES_REDIRECT_URI: "${REDIRECT_URI}"

      # CORS
      CORS_PROPERTIES_CORS_ALLOWED_ORIGINS_URI: "${CORS_ALLOWED_ORIGINS_URI}"

      TZ: "Asia/Novosibirsk"
    ports:
      - "4040:8080"
    restart: unless-stopped
    networks:
      - gearit-network

  victoria-metrics:
    container_name: gearit-victoria
    image: victoriametrics/victoria-metrics
    environment:
      TZ: "Asia/Novosibirsk"
    ports:
      - "8428:8428"
    command:
      - '-retentionPeriod=1'
    networks:
      - gearit-network

  vmagent:
    container_name: gearit-vmagent
    image: victoriametrics/vmagent
    command:
      - '-promscrape.config=/etc/prometheus/scrape.yml'
      - '-remoteWrite.url=http://gearit-victoria:8428/api/v1/write'
    volumes:
      - ./prometheus/:/etc/prometheus/
    networks:
      - gearit-network

  grafana:
    container_name: gearit-grafana
    image: grafana/grafana
    environment:
      TZ: "Asia/Novosibirsk"
    ports:
      - "8008:3000"
    networks:
      - gearit-network

networks:
  gearit-network:
