create table IF NOT EXISTS gearit_user_provider
(
    id            bigint generated by default as identity primary key,
    password      varchar not null,
    provider      varchar not null,
    default_email varchar not null unique,
    is_confirmed  boolean not null,
    account_id    bigint constraint fk_user_provider_account references gearit_account_info
);

create table IF NOT EXISTS gearit_account_info
(
    id           bigint generated by default as identity primary key,
    firstname    varchar,
    middlename   varchar,
    lastname     varchar,
    phone_number varchar,
    gender       varchar,
    birth_date   timestamp
);

alter table gearit_user_provider
    owner to gearit;

alter table gearit_account_info
    owner to gearit;

INSERT INTO
    gearit_account_info(firstname, middlename, lastname, phone_number, gender, birth_date)
VALUES (
        'Admin',
        'Admin',
        'Admin',
        '+7-(951)-241-94-31',
        'MALE',
        '2025-06-02 23:06:38.000000'
       )
ON CONFLICT DO NOTHING;

INSERT INTO
    gearit_user_provider(password, provider, default_email, is_confirmed, account_id)
VALUES (
        '$2a$10$Sm84Sv55ksAup6AIH/zoW.WGX4VxrkoSKjncJTgcaqxqAg60d/fQq',
        'INTERNAL',
        'admin@mail.ru',
        TRUE,
        1
       )
ON CONFLICT DO NOTHING
