create table IF NOT EXISTS gearit_user_provider
(
    id            bigint generated by default as identity primary key,
    password      varchar not null,
    provider      varchar not null,
    default_email varchar not null unique,
    is_confirmed  boolean not null
);

alter table gearit_user_provider
    owner to gearit;

INSERT INTO
    gearit_user_provider(password, provider, default_email, is_confirmed)
VALUES (
        '$2a$10$Sm84Sv55ksAup6AIH/zoW.WGX4VxrkoSKjncJTgcaqxqAg60d/fQq',
        'INTERNAL',
        'admin@mail.ru',
        TRUE
       )
