name: Публикация образа backend-a и рестарт сервиса
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Cache Jib Docker layers
        uses: actions/cache@v4
        with:
          path: ~/.cache/jib
          key: jib-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            jib-${{ runner.os }}-

      - name: Build and push docker image
        run: ./gradlew jib \
          -Djib.to.auth.username=${{ github.actor }} \
          -Djib.to.auth.password=${{ secrets.DOCKER_PASSWORD }}
