name: Публикация образа backend-a и рестарт сервиса
on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build and push docker image
        run: |
          ./gradlew jib -Djib.to.auth.username=${{ github.actor }} -Djib.to.auth.password=${{ secrets.GITHUB_TOKEN }}
