name: Проверка корректности содержимого файла openapi
on:
  push:
    paths:
      - openapi.gearit.yaml

jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
      - name: OpenAPI Lint Checks
        uses: nwestfall/openapi-action@v1.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          file: openapi.gearit.yaml