name: Проверка корректности содержимого openapi
on:
  push:
    paths:
      - openapi.gearit.yaml

jobs:
  build:
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Lint OpenAPI
        run: redocly lint openapi.gearit.yaml
